---
- name: 🚀 Feature
  description: Feature added in the PR
  color: F10505
- name: 🕵🏻 Fix
  description: Fix applied in the PR
  color: F4D03F
- name: ⚠️ Breaking Change
  description: Breaking change in the PR
  color: F1F800
- name: 🤩 size/xs
  description: Pull request size XS
  color: 27AE60
- name: 🥳 size/s
  description: Pull request size S
  color: 2ECC71
- name: 😎 size/m
  description: Pull request size M
  color: F1C40F
- name: 😖 size/l
  description: Pull request size L
  color: F39C12
- name: 🤯 size/xl
  description: Pull request size XL
  color: E67E22
